Repository OpenMS/pyopenms_viz, pull requests merged in 2024-09, with the labels that each got.

#19 Patch/spectrum bin peaks
  pyopenms_viz/_core.py
  pyopenms_viz/_misc.py
Labels: enhancement, Review effort [1-5]: 3

#22 Tutorials
  nbs/alphatims_tutorial.ipynb
  nbs/manuscript_gallery.ipynb
  nbs/pymzml_tutorial.ipynb
  nbs/pyopenms_tutorial.ipynb
  nbs/pyteomics_tutorial.ipynb
  nbs/timsrust_pyo3_tutorial.ipynb
Labels: documentation, Review effort [1-5]: 2

#26 remove: python 3.9 from project toml
  pyproject.toml
Labels: Review effort [1-5]: 1, configuration changes

#23 change binning aggregation from "mean" to "sum"
  nbs/FullSpectrumPlotting.ipynb
  nbs/Spectrum.ipynb
  nbs/alphatims_tutorial.ipynb
  pyopenms_viz/_core.py
  pyopenms_viz/_misc.py
Labels: enhancement, Review effort [1-5]: 2

#31 Docs first version
  .gitignore
  .readthedocs.yaml
  docs/API.rst
  docs/Chromatogram.rst
  docs/Installation.rst
  docs/Mobilogram.rst
  docs/PeakMap.rst
  docs/README.md
  docs/Spectrum.rst
  docs/User Guide.rst
  docs/_static/OpenMS.svg
  docs/_static/custom.css
  docs/_static/switcher.json
  docs/chromatogramPlot.tsv
  docs/conf.py
  docs/gallery_scripts_template/GALLERY_HEADER.rst
  docs/gallery_scripts_template/GALLERY_HEADER_ms_bokeh.rst
  docs/gallery_scripts_template/GALLERY_HEADER_ms_matplotlib.rst
  docs/gallery_scripts_template/GALLERY_HEADER_ms_plotly.rst
  docs/gallery_scripts_template/plot_chromatogram.py
  docs/gallery_scripts_template/plot_investigate_spectrum_binning_ms_matplotlib.py
  docs/gallery_scripts_template/plot_mobilogram.py
  docs/gallery_scripts_template/plot_peakmap.py
  docs/gallery_scripts_template/plot_peakmap_marginals.py
  docs/gallery_scripts_template/plot_spectrum_dia.py
  docs/img/pyOpenMSviz_logo_color.png
  docs/index.rst
  docs/mobilogramPlot.tsv
  docs/peakMapPlot.tsv
  docs/requirements.txt
  docs/spectrumPlot.tsv
  docs/templates/class.rst
  pyopenms_viz/_bokeh/__init__.py
  pyopenms_viz/_bokeh/core.py
  pyopenms_viz/_core.py
  pyopenms_viz/_matplotlib/__init__.py
  pyopenms_viz/_matplotlib/core.py
  pyopenms_viz/_plotly/__init__.py
  pyopenms_viz/_plotly/core.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#33 remove explcit TOC
  docs/index.rst
Labels: documentation, Review effort [1-5]: 1

#40 Patch/html annotation bug
  pyopenms_viz/_bokeh/core.py
  pyopenms_viz/_matplotlib/core.py
  pyopenms_viz/_plotly/core.py
Labels: bug, bug fix
